name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - name: debug working dir
      run: ls -lah
    - name: All tests
      run: ./parallel-tools/test.sh
