name: tests

on:
  pull_request:
    branches:
      - master

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
    - name: debug working dir  
      run: ls -lah
    - name: All tests
      run: ./test.sh
